CREATE TABLE IF NOT EXISTS Doctor (
  id INT NOT NULL SERIAL PRIMARY KEY,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  speciality VARCHAR(15) NOT NULL,
  phone_number VARCHAR(45) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
;
CREATE TABLE IF NOT EXISTS Patient (
  id INT NOT NULL SERIAL PRIMARY KEY,
  first_name VARCHAR(45) NOT NULL,
  last_name VARCHAR(45) NOT NULL,
  date_of_birth DATE NOT NULL,
  gender VARCHAR(10) NOT NULL,
  phone_number VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  address VARCHAR(45) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Appointment (
  id INT NOT NULL SERIAL PRIMARY KEY,
  doctor_id  INT NOT NULL,
  patient_id INT NOT NULL,
  appointment_date TIMESTAMP NOT NULL,
  status VARCHAR(15) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (doctor_id) REFERENCES Doctor(id),
  FOREIGN KEY (patient_id) REFERENCES Patient(id)
);